### PR TITLE
Add type hints and pre-commit hooks.

### PR DESCRIPTION
**Pull request by greschd**
It's happening: #convergence :ok_hand:

Add complete type hints for this sub-module, checked with strict ``mypy`` settings. Dropping support for older Python versions, lowest supported is now ``3.6``.

Adds ``prospector``, ``yapf`` and ``mypy`` as pre-commit hooks.

### CODE REVIEW

**Comment by mskoenz** [comment]
Isnt dropping support for all `<3.6` a bit aggressive?
What are the advantages using typing here (aside from being state of the art)?

**Comment by greschd** [comment]
It's not like the old version will stop working, though -- the ``python_requires`` marker in ``setup.py`` should ensure that it keeps installing smoothly on older versions.

This enables typing in downstream projects, without needing to explicitly ignore the missing ``fsc.export`` import.

**Comment by mskoenz** [comment]
So if it works for `<3.6` why the lowest supported is now `3.6` comment?
If 2.7 and 3.5 work, we should include them in the travis files, no?

**Comment by greschd** [comment]
But yeah, this is not _super_ important.. mostly it's a "because I wanted to" change 🤣

**Comment by greschd** [comment]
2.7 and 3.5 should gracefully install an older version of ``fsc.export``, not work with the current version.

**Comment by mskoenz** [comment]
I'm more than fine to keep up with the latest features ^^

**Comment by greschd** [comment]
Will need to test this on testpypi though, because locally the install still went through...

**Comment by mskoenz** [comment]
Can we have an automated test for that? Not super stoked about supporting stuff without CI (even though it will not update anymore)

**Comment by greschd** [comment]
Sure can.

**Comment by mskoenz** [comment]
If we can have CI for the graceful installation of older versions, this merge request is a no-brainer!

**Comment by greschd** [comment]
Hmm... well, we can have CI, but we will only know if it worked after pushing the new version to PyPI 😆

**Comment by mskoenz** [comment]
(I have 40+ repos which support 3.5 and use fsc.export)

**Comment by mskoenz** [comment]
Fair, we can merge and publish if accidental errors will be fixed

**Comment by mskoenz** [comment]
(I will peer-review now)

**Comment by greschd** [comment]
I'll make it a ``dev`` version on PyPI, that way we can be sure before publishing an actual version.

**Comment by mskoenz** [comment]
```
mktmpenv #(3.7)
git clone
pip install -e .
pre-commit install
pre-commit run --all-files
```

yields

```
An error has occurred: InvalidConfigError:
=====> /Users/mskoenz/programming/hobby/frescolino/pyexport/.pre-commit-config.yaml does not exist
Check the log at /Users/mskoenz/.cache/pre-commit/pre-commit.log
```

**Comment by mskoenz** [comment]
or were you referring to other hooks, not used by the [dev]user?

**Comment by greschd** [comment]
Are you on the right branch? ``.pre-commit-config.yaml`` is here: https://github.com/FrescolinoGroup/pyexport/pull/2/files#diff-82c3b36709926de3a1b27bea0d8258cc

**Comment by greschd** [comment]
You'll need to install the ``[precommit]`` extra, though.

**Comment by greschd** [comment]
Probably best to wait with reviewing until I've figured out the CI, though.

**Comment by greschd** [comment]
I think I might need to first make a release of the old version including the ``python_requires`` flag.

**Comment by mskoenz** [comment]
Was on the wrong branch :/ fail

**Comment by mskoenz** [comment]
Why do you need [precommit]? The precommit plugins should install themself on `pre-commit install`... or is it just more ecomomical this way?

**Comment by mskoenz** [comment]
I will close this pull request and wait for a new one

**Comment by greschd** [comment]
The ``prospector`` and ``mypy`` hooks are run as "system" commands - meaning the _won't_ install themselves with pre-commit. Reason for that being that I got fed up with random issues because of how they were invoked.

**Comment by mskoenz** [comment]
Isnt this enough to get prospector?

```
- repo: git://github.com/guykisel/prospector-mirror
  sha: b27f281eb9398fc8504415d7fbdabf119ea8c5e1
  hooks:
  - id: prospector
    language: system
    exclude: '^(doc/)|(examples/)|(futures/)'
```

**Comment by greschd** [comment]
In principle, yes. But it can mess up with different versions (of its dependencies, I guess) being installed. I've found manual install + call to be more reproducible overall.

**Pull request closed without merging**
