### PR TITLE
Add 'python_requires' on old version.

### PR DESCRIPTION
**Pull request by greschd**
This is required for the "graceful fallback" to work once we publish a version with a higher "python_requires". Relevant info here: https://packaging.python.org/guides/dropping-older-python-versions/#dropping-a-python-release

### CODE REVIEW

**Comment by mskoenz** [comment]
This is more FYI:
(on support_branch) Running `pip install .` on py27 installs (`pip freeze`):
```
fsc==0.0.2
fsc.export==1.1.1
fsc.formatting==1.0.0
singledispatch==3.4.0.3
six==1.13.0
```
On py37:
```
fsc.export==1.1.1
```

**Comment by mskoenz** [comment]
Install and tests work on py27 py36, and py37, merge accepted

**Comment by mskoenz** [comment]
@greschd delete branch at your convenience

**Comment by greschd** [comment]
>
> This is more FYI:
> (on support_branch) Running `pip install .` on py27 installs (`pip freeze`):
> 
> ```
> fsc==0.0.2
> fsc.export==1.1.1
> fsc.formatting==1.0.0
> singledispatch==3.4.0.3
> six==1.13.0
> ```
> 
> On py37:
> 
> ```
> fsc.export==1.1.1
> ```

I think that is intentional.. for some reason the namespace package didn't quite work on py27 if the base ``fsc`` wasn't there.

**Pull request merged**
